
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 25 20:26:12 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 27;
  public static final int CONST = 8;
  public static final int NUMCONST = 47;
  public static final int LPAREN = 16;
  public static final int SEMI = 9;
  public static final int CONTINUE = 20;
  public static final int LSS = 40;
  public static final int LCBRACE = 6;
  public static final int MINUS = 25;
  public static final int RCBRACE = 7;
  public static final int STAR = 26;
  public static final int RPAREN = 17;
  public static final int AND = 41;
  public static final int RECORD = 18;
  public static final int OR = 42;
  public static final int COMMA = 11;
  public static final int CLASS = 14;
  public static final int PERC = 28;
  public static final int INC = 21;
  public static final int PLUS = 24;
  public static final int ASSIGN = 10;
  public static final int IF = 33;
  public static final int THIS = 3;
  public static final int DOT = 23;
  public static final int EOF = 0;
  public static final int RETURN = 30;
  public static final int EQUAL = 35;
  public static final int SUPER = 4;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int IDENT = 45;
  public static final int BREAK = 19;
  public static final int GTE = 37;
  public static final int COLON = 2;
  public static final int LBRACE = 12;
  public static final int ELSE = 34;
  public static final int READ = 31;
  public static final int CHARCONST = 48;
  public static final int WHILE = 44;
  public static final int LSSE = 39;
  public static final int RBRACE = 13;
  public static final int BOOLCONST = 46;
  public static final int EXTENDS = 15;
  public static final int PROG = 5;
  public static final int DIFF = 36;
  public static final int DEC = 22;
  public static final int GT = 38;
  public static final int DO = 43;
  public static final int PRINT = 32;
}

